[config]
# Se quiser recarregar apps GTK automaticamente (pode causar flash branco em alguns apps)
reload_apps = true

# Define o modo escuro como preferência padrão
color_scheme = "dark"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/dank-colors.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/dank-colors.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors/matugen-colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen_colors.conf'
output_path = '~/.config/hypr/matugen_colors.conf'